name: CI

# on: 
#   push:
#     branches:    
#       - master 

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [14.x]
    
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: install
      run: |
        npm install
    - name: test
      run: |
        npm test 
      env:
        CI: true
      
    - name: build
      run: |
        npm run build --if-present